/****************************************
 * Generated by c4tcl (c) Cyril BARBATO *
 * from calling TCL _C_ function.       *
 * ** DISCLAIMER FROM ALL WARRANTIES ** *
 ****************************************/
#include <stdlib.h>
#ifndef _TCL
#include <tcl.h>
#endif
/******************
 * libc4tcl main entry point prototype
 */
int libc4tcl_main (Tcl_Interp *interp, int argc, char **argv);

    #ifdef _WIN32
    #define _WIN32_WINNT 0x0500
    #include <windows.h>
    #endif
    #include <stdio.h>
    #include <stdlib.h>
    
/******************
 * exampleAddCmd : function exampleCmd
 */
int exampleAddCmd (ClientData data, Tcl_Interp *interp, int argc, char **argv) {
//  get var values
    int a = (int) atoi(argv[1]);
    int b = (int) atoi(argv[2]);
//  result
    sprintf(interp->result, "%d", a + b);
    return TCL_OK;
}
/******************
 * Main entry point
 */
int libc4tcl_main (Tcl_Interp *interp, int argc, char **argv) {
    //  example Add Command
    Tcl_CreateCommand(interp, "example_add", (Tcl_CmdProc *) exampleAddCmd, NULL, NULL);
    return TCL_OK;
}
#    //END _C_ FUNCTIONS SECTION

/******************
 * TCL Library Init (real) entry point
 */
int C4tcltmp_Init (Tcl_Interp *interp) {
/*init classic C arguments from environnement variable*/
int argc=1;
char *p=NULL;
char *argv[1024];
argv[0]=getenv("LIBC4TCL_ARGS");
for (p=argv[0];*p!=0;p++) {
	if (*p==0x20) {
		*p=0;
		argv[(++argc-1)]=++p;
	}
}
/******************
 * libc4tcl main entry point
 */
libc4tcl_main(interp,argc,argv);
return TCL_OK;
}
